backend:
  name: git-gateway
  repo: ingvoo/ljomi
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'content/articles'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - {
          label: 'Published',
          name: 'published',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Date',
          name: 'createdAt',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: false,
          hint: 'This field overwrites the default createdAt value. Which is often set to current date instead of the date when the post really was created or published',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'recommendations'
    label: 'Recommendations'
    folder: 'content/recommendations'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Person', name: 'person', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Organization', name: 'organization', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
